# human breast cancer growing on nude mice
comment: Detect and quantify BSJ in eCLIP (has to be paired end. fuck)
workdir: /tscc/lustre/ddn/scratch/hsher/circ_HEK293_RBM15_eCLIP
menifest: /tscc/nfs/home/hsher/projects/circSTAMP_pipe/notebook/HEK_RBM15_eCLIP.csv

GFF: /tscc/nfs/home/hsher/gencode_coords/gencode.v35.basic.annotation.gff3  
GTF: /tscc/nfs/home/hsher/gencode_coords/gencode.v35.basic.annotation.gtf  
GENOMEFA: /tscc/nfs/home/hsher/gencode_coords/GRCh38.primary_assembly.genome.fa
GENOMEFAI: /tscc/nfs/home/hsher/gencode_coords/GRCh38.primary_assembly.genome.fa.fai
BWA_INDEX: /tscc/projects/ps-yeolab5/hsher/Tao_circSTAMP/bwa_gencode35
HISAT_INDEX: /tscc/projects/ps-yeolab5/hsher/Tao_circSTAMP/hisat_gencode35
STAR_INDEX: /tscc/projects/ps-yeolab5/hsher/Tao_circSTAMP/star_2_7_gencode35
INDEX_NAME: HG38


READ1_ADAPTOR: /tscc/projects/ps-yeolab4/software/eclip/0.7.0/examples/inputs/InvRNA1_adapters.fasta
READ2_ADAPTOR:  /tscc/projects/ps-yeolab4/software/eclip/0.7.0/examples/inputs/InvRiL19_adapters.fasta
# settings for Ciri
CIRICONFIG: /tscc/nfs/home/hsher/projects/circSTAMP_pipe/ciriconfig_full_tscc2.yaml
CIRCRIP_PATH: /home/hsher/bin/circRIP
LIBRARY_TYPE: 2 #Library type, 0: unstranded, 1: read1 match the sense strand, 2: read1 match the antisense strand (default: 0)

# ANALYSIS # cut -f 1,2 genome.fa.fai > chrom.sizes
CHROM_SIZE: /tscc/nfs/home/hsher/gencode_coords/GRCh38.primary_assembly.chrom.sizes
ANNOTATOR_SPECIES: GRCh38
GTFDB: /tscc/nfs/home/hsher/gencode_coords/gencode.v35.gtf.db
edit_thres: 0.9999
EXPAND_LEN: 30

# circRIP
SCRIPT_PATH: /tscc/nfs/home/hsher/projects/circSTAMP_pipe/scripts

# eCLIP specific
UMI_SIZE: 10