verbose: true
notemp: true
latency: 60
printshellcmds: true
skip-script-cleanup: true
nolock: true
keep-going: true
use-singularity: true
singularity-prefix: /tscc/lustre/ddn/scratch/hsher/singularity/
singularity-args: "--bind /tscc"
use-conda: true
conda-prefix: "/tscc/nfs/home/hsher/snakeconda"
conda-frontend: mamba
jobs: 8