comment: basic analysis for protocol, cell line and organoids
workdir: /tscc/nfs/home/hsher/scratch/tao_basic_nextera
menifest: /tscc/nfs/home/hsher/projects/circSTAMP_pipe/notebook_protocol/fastq_csv/1_basic_nextera.csv

GFF: /tscc/nfs/home/hsher/gencode_coords/gencode.v35.basic.annotation.gff3  
GTF: /tscc/nfs/home/hsher/gencode_coords/gencode.v35.basic.annotation.gtf 
GENOMEFA: /tscc/nfs/home/hsher/gencode_coords/GRCh38.primary_assembly.genome.fa
GENOMEFAI: /tscc/nfs/home/hsher/gencode_coords/GRCh38.primary_assembly.genome.fa.fai
BWA_INDEX: /tscc/projects/ps-yeolab5/hsher/Tao_circSTAMP/bwa_gencode35
HISAT_INDEX: /tscc/projects/ps-yeolab5/hsher/Tao_circSTAMP/hisat_gencode35
STAR_INDEX: /tscc/projects/ps-yeolab5/hsher/Tao_circSTAMP/star_2_7_gencode35
INDEX_NAME: HG38


READ1_ADAPTOR: /tscc/nfs/home/hsher/projects/circSTAMP_pipe/input/nextera.fasta
READ2_ADAPTOR:  /tscc/nfs/home/hsher/projects/circSTAMP_pipe/input/nextera.fasta

# settings for Ciri
CIRICONFIG: /tscc/nfs/home/hsher/projects/circSTAMP_pipe/ciriconfig_full_tscc2.yaml
LIBRARY_TYPE: 0 #Library type, 0: unstranded, 1: read1 match the sense strand, 2: read1 match the antisense strand (default: 0)

# ANALYSIS # cut -f 1,2 genome.fa.fai > chrom.sizes
CHROM_SIZE: /tscc/nfs/home/hsher/gencode_coords/GRCh38.primary_assembly.chrom.sizes

# circRIP
SCRIPT_PATH: /tscc/nfs/home/hsher/projects/circSTAMP_pipe/scripts
CIRCRIP_PATH: /tscc/nfs/home/hsher/bin/circRIP # where you downloaded https://github.com/bioinfolabwhu/circRIP/
RIP_comparison: # Here you specify what to use a background and what to use as input, these names have to be in manifest['Sample']

fit_overdispersion_from: 

# STAMP
STAMP:

STAMP_control:

external_stamp_control:

# differential expression and shit
circ_de:
  HepG2_vs_HEK:
    ctrl:
      - HEK_rep1_rar11
      - HEK_rep2_rar11
    case:
      - HepG2_rep1_rar11
      - HepG2_rep2_rar11
  K562_vs_HEK:
    ctrl:
      - HEK_rep1_rar11
      - HEK_rep2_rar11
    case:
      - K562_rep1_rar11
      - K562_rep2_rar11
  HeLa_vs_HEK:
    ctrl:
      - HEK_rep1_rar11
      - HEK_rep2_rar11
    case:
      - HeLa_rep1_rar11
      - HeLa_rep2_rar11

external_de_paths: